### PR TITLE
Colored levels optioned added,

### PR DESCRIPTION
**Pull request by Link2Twenty**
- Updated documentation to reflect change
- Uploaded new screenshot
- Each stage can be styled with custom styles
- Added custom style option for default color
- Updated demo page to show new functionality

### CODE REVIEW

**Comment by Protoss78** [comment]
Awesome. Thanks for the PR.

**Comment by Link2Twenty** [comment]
Do you need me to change something before you merge? Or are you just looking it over? (Just noticed it's closed not merged)

**Comment by Protoss78** [comment]
Sorry, I reviewed it on my cell and must have pushed the wrong button. Probably shouldn't have done that on public transport in the first place. :-)

**Comment by Link2Twenty** [comment]
I thought that might be the case :-) thanks

**Pull request merged**
